### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by frainfreeze** [frainfreeze/studying#1]
- [x] make a release after first semester
- [x] new summaries
- [x] networking homework
- [x] update main read-me

**Comment by frainfreeze** [comment]
- [ ] finish BC++TGP
- [ ] main game proj
- [ ] finish and push reference

**Comment by frainfreeze** [comment]
- [ ] tidy up blog
- [ ] add books to the blogs bookshelf

**Comment by frainfreeze** [comment]
- [ ] make a release after the second semester
- [ ] summaries
- [ ] bcpptgp
- [ ]  clean repo && tidy up repo structure
