### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by frainfreeze** [frainfreeze/studying#2]
**Programming**
- [ ] Programming Principles and Practice Using C++ by Bjarne Stroustrup (20%)
- [ ] The Self-taught Programmer by Cory Althoff
- [ ] Computer Science Distilled: Learn the Art of Solving Computational Problems
- [ ] The Mythical Man-Month
- [ ] Joel on Software: And on etcetcetc
- [ ] Programming Pearls
- [ ] Code: The Hidden Language of Computer Hardware and Software

**The C++**
- [ ]  Beginning C++ Through Game Programming by Michael Dawson (60%)
- [ ] edX Microsoft: DEV210.2x - Intermediate C++, DEV210x - Introduction to C++ (50%)
- [ ] Udacity C++ For Programmers (ft. Bjarne Stroustrup) (30%)
- [ ] Udemy C++ Tutorial for Complete Beginners (30%)
- [ ]  How to Think Like a Computer Scientist C++ Version by Allen B. Downey

**Other**
- [ ] clojure?
- [ ] revise python?
- [x] blog?

**Comment by frainfreeze** [comment]
keep in sync with https://frainfreeze.github.io/other/programer-roadmap/ !

**Comment by frainfreeze** [comment]
moved to discord pin.
