### ISSUE TITLE
Roadmap 2

### ISSUE THREAD

**Issue by frainfreeze** [frainfreeze/studying#5]
**Programming**
- [ ] Introduction to algorithms

**The C++**
- [ ] C++ Primer by Stanley Lippman, Josée Lajoie, and Barbara E. Moo
- [ ] A Tour of C++ by Bjarne Stroustrup
- [ ] Accelerated C++ by Andrew Koenig and Barbara Moo
- [ ] the c++ programming lang 4th ed (Bjarne Stroustrup)

**Comment by frainfreeze** [comment]
keep in sync with https://frainfreeze.github.io/other/programer-roadmap/ !

**Comment by frainfreeze** [comment]
moved to discord pin
